include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
    prefer_const_constructors: ignore
    prefer_interpolation_to_compose_strings: ignore
    curly_braces_in_flow_control_structures: ignore
    sized_box_for_whitespace: ignore
    avoid_print: ignore
