include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Common noisy rules → warnings only
    use_build_context_synchronously: warning
    prefer_const_constructors: warning
    prefer_interpolation_to_compose_strings: warning
    curly_braces_in_flow_control_structures: warning
    sized_box_for_whitespace: warning

    # Ignore console logging in production
    avoid_print: ignore
