name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure Gradle wrapper is executable
      - name: Fix gradlew permissions
        run: chmod +x android/gradlew

      # Setup Java for Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # match your version
          channel: stable
          cache: true

      # Verify installation
      - name: Flutter Doctor
        run: flutter doctor -v

      # Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Build App Bundle
      - name: Build App Bundle
        run: flutter build appbundle --release

      # Build Web
      - name: Build Web App
        run: flutter build web --release

      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: babycareapp-artifacts
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
            build/web/
