name: Flutter Baby Care App CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.0'
  JAVA_VERSION: '11'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Verify the installation
        run: flutter doctor -v

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build-android:
    name: Build Android
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-web:
    name: Build and Deploy Web
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          channel: 'stable'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/babycareapp/"

      - name: Upload web artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  release:
    name: Create Release
    needs: [build-android, build-web]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=v$VERSION" >> $GITHUB_OUTPUT

      - name: Download APK artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: ./apk

      - name: Download AAB artifact
        uses: actions/download-artifact@v3
        with:
          name: android-aab
          path: ./aab

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.TAG }}
          name: Baby Care App ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./apk/*.apk
            ./aab/*.aab
          body: |
            ## Baby Care App Release ${{ steps.version.outputs.VERSION }}
            
            ### Downloads
            - **APK**: Ready for sideloading
            - **AAB**: Ready for Google Play Store
            - **Web**: Deployed to GitHub Pages
            
            ### Changes
            - See commit history for detailed changes
            
            ### Installation
            - Download the APK for direct installation
            - Use AAB for Play Store deployment
            - Access web version at: https://dhiya03.github.io/babycareapp/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}